In [136]:
import pandas as pd
import joblib as jb                  # Use to import or save a model

In [137]:
df=pd.read_csv("laptopPrice.csv")    # Read a file
df

brand processor_brand  ... Number of Ratings Number of Reviews
0      ASUS           Intel  ...                 3                 0
1    Lenovo           Intel  ...                65                 5
2    Lenovo           Intel  ...                 8                 1
3      ASUS           Intel  ...                 0                 0
4      ASUS           Intel  ...                 0                 0
..      ...             ...  ...               ...               ...
818    ASUS             AMD  ...                 0                 0
819    ASUS             AMD  ...                 0                 0
820    ASUS             AMD  ...                 0                 0
821    ASUS             AMD  ...                 0                 0
822  Lenovo             AMD  ...                18                 4

[823 rows x 19 columns]

In [138]:
df.head() # Default 5 rows from start


brand processor_brand  ... Number of Ratings Number of Reviews
0    ASUS           Intel  ...                 3                 0
1  Lenovo           Intel  ...                65                 5
2  Lenovo           Intel  ...                 8                 1
3    ASUS           Intel  ...                 0                 0
4    ASUS           Intel  ...                 0                 0

[5 rows x 19 columns]

In [139]:
df.info()   # Information of dataset

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 823 entries, 0 to 822
Data columns (total 19 columns):
 #   Column             Non-Null Count  Dtype 
---  ------             --------------  ----- 
 0   brand              823 non-null    object
 1   processor_brand    823 non-null    object
 2   processor_name     823 non-null    object
 3   processor_gnrtn    823 non-null    object
 4   ram_gb             823 non-null    object
 5   ram_type           823 non-null    object
 6   ssd                823 non-null    object
 7   hdd                823 non-null    object
 8   os                 823 non-null    object
 9   os_bit             823 non-null    object
 10  graphic_card_gb    823 non-null    object
 11  weight             823 non-null    object
 12  warranty           823 non-null    object
 13  Touchscreen        823 non-null    object
 14  msoffice           823 non-null    object
 15  Price              823 non-null    int64 
 16  rating             823 non-null    object
 1

In [140]:
df.describe() # Information of numerical data

Price  Number of Ratings  Number of Reviews
count     823.000000         823.000000         823.000000
mean    76745.177400         315.301337          37.609964
std     45101.790525        1047.382654         121.728017
min     16990.000000           0.000000           0.000000
25%     46095.000000           0.000000           0.000000
50%     64990.000000          17.000000           2.000000
75%     89636.000000         139.500000          18.000000
max    441990.000000       15279.000000        1947.000000

In [141]:
df.tail() # Default 5 rows from end

brand processor_brand  ... Number of Ratings Number of Reviews
818    ASUS             AMD  ...                 0                 0
819    ASUS             AMD  ...                 0                 0
820    ASUS             AMD  ...                 0                 0
821    ASUS             AMD  ...                 0                 0
822  Lenovo             AMD  ...                18                 4

[5 rows x 19 columns]

In [142]:
df.dtypes # Datatype

brand                object
processor_brand      object
processor_name       object
processor_gnrtn      object
ram_gb               object
ram_type             object
ssd                  object
hdd                  object
os                   object
os_bit               object
graphic_card_gb      object
weight               object
warranty             object
Touchscreen          object
msoffice             object
Price                 int64
rating               object
Number of Ratings     int64
Number of Reviews     int64
dtype: object

In [143]:
df.shape   # Shape of dataset

(823, 19)

In [144]:
df.columns  # Shows features of the dataset

Index(['brand', 'processor_brand', 'processor_name', 'processor_gnrtn',
       'ram_gb', 'ram_type', 'ssd', 'hdd', 'os', 'os_bit', 'graphic_card_gb',
       'weight', 'warranty', 'Touchscreen', 'msoffice', 'Price', 'rating',
       'Number of Ratings', 'Number of Reviews'],
      dtype='object')

In [145]:
num_columns=df.select_dtypes(exclude='O')    # For numerical data
num_columns

Price  Number of Ratings  Number of Reviews
0     34649                  3                  0
1     38999                 65                  5
2     39999                  8                  1
3     69990                  0                  0
4     26990                  0                  0
..      ...                ...                ...
818  135990                  0                  0
819  144990                  0                  0
820  149990                  0                  0
821  142990                  0                  0
822   57490                 18                  4

[823 rows x 3 columns]

In [146]:
cat_columns=df.select_dtypes(include='O')    # For categorial data
cat_columns

brand processor_brand processor_name  ... Touchscreen msoffice   rating
0      ASUS           Intel        Core i3  ...          No       No  2 stars
1    Lenovo           Intel        Core i3  ...          No       No  3 stars
2    Lenovo           Intel        Core i3  ...          No       No  3 stars
3      ASUS           Intel        Core i5  ...          No       No  3 stars
4      ASUS           Intel   Celeron Dual  ...          No       No  3 stars
..      ...             ...            ...  ...         ...      ...      ...
818    ASUS             AMD        Ryzen 9  ...          No       No  3 stars
819    ASUS             AMD        Ryzen 9  ...          No       No  3 stars
820    ASUS             AMD        Ryzen 9  ...          No       No  3 stars
821    ASUS             AMD        Ryzen 9  ...          No       No  3 stars
822  Lenovo             AMD        Ryzen 5  ...          No       No  4 stars

[823 rows x 16 columns]

we can only train model on numerical data


In [147]:
cat_columns.head()

brand processor_brand processor_name  ... Touchscreen msoffice   rating
0    ASUS           Intel        Core i3  ...          No       No  2 stars
1  Lenovo           Intel        Core i3  ...          No       No  3 stars
2  Lenovo           Intel        Core i3  ...          No       No  3 stars
3    ASUS           Intel        Core i5  ...          No       No  3 stars
4    ASUS           Intel   Celeron Dual  ...          No       No  3 stars

[5 rows x 16 columns]

In [148]:
num_columns.head()

Price  Number of Ratings  Number of Reviews
0  34649                  3                  0
1  38999                 65                  5
2  39999                  8                  1
3  69990                  0                  0
4  26990                  0                  0

In [149]:
cat_columns["brand"].unique()   # Unique value

array(['ASUS', 'Lenovo', 'acer', 'Avita', 'HP', 'DELL', 'MSI', 'APPLE'],
      dtype=object)

In [150]:
cat_columns["brand"].nunique()    # No of unique value

8

In [151]:
cat_columns['brand']     # Particular column

0        ASUS
1      Lenovo
2      Lenovo
3        ASUS
4        ASUS
        ...  
818      ASUS
819      ASUS
820      ASUS
821      ASUS
822    Lenovo
Name: brand, Length: 823, dtype: object

In [152]:
cat_columns["processor_brand"].unique()    # Unique value

array(['Intel', 'AMD', 'M1'], dtype=object)

In [153]:
cat_columns["processor_brand"].nunique()

3

In [154]:
cat_columns["processor_name"].unique()    # Unique value

array(['Core i3', 'Core i5', 'Celeron Dual', 'Ryzen 5', 'Core i7',
       'Core i9', 'M1', 'Pentium Quad', 'Ryzen 3', 'Ryzen 7', 'Ryzen 9'],
      dtype=object)

In [155]:
cat_columns["processor_name"].nunique()

11

In [156]:
cat_columns["processor_gnrtn"].unique()

array(['10th', 'Not Available', '11th', '7th', '8th', '9th', '4th',
       '12th'], dtype=object)

In [157]:
cat_columns["processor_gnrtn"].nunique()

8

In [158]:
cat_columns["ram_gb"].unique()

array(['4 GB', '8 GB', '16 GB', '32 GB'], dtype=object)

In [159]:
cat_columns["ram_gb"].nunique()

4

In [160]:
cat_columns["ram_type"].unique()

array(['DDR4', 'LPDDR4', 'LPDDR4X', 'DDR5', 'DDR3', 'LPDDR3'],
      dtype=object)

In [161]:
cat_columns["ram_type"].nunique()

6

In [162]:
cat_columns["ssd"].unique()

array(['0 GB', '512 GB', '256 GB', '128 GB', '1024 GB', '2048 GB',
       '3072 GB'], dtype=object)

In [163]:
cat_columns["ssd"].nunique()

7

In [164]:
cat_columns["hdd"].unique()

array(['1024 GB', '0 GB', '512 GB', '2048 GB'], dtype=object)

In [165]:
cat_columns["hdd"].nunique()

4

In [166]:
cat_columns["os"].nunique()

3

In [167]:
cat_columns["os_bit"].unique()

array(['64-bit', '32-bit'], dtype=object)

In [168]:
cat_columns["os_bit"].nunique()

2

In [169]:
cat_columns.columns

Index(['brand', 'processor_brand', 'processor_name', 'processor_gnrtn',
       'ram_gb', 'ram_type', 'ssd', 'hdd', 'os', 'os_bit', 'graphic_card_gb',
       'weight', 'warranty', 'Touchscreen', 'msoffice', 'rating'],
      dtype='object')

In [170]:
cat_columns["graphic_card_gb"].unique()

array(['0 GB', '2 GB', '4 GB', '6 GB', '8 GB'], dtype=object)

In [171]:
cat_columns["graphic_card_gb"].nunique()

5

In [172]:
cat_columns["weight"].unique()

array(['Casual', 'ThinNlight', 'Gaming'], dtype=object)

In [173]:
cat_columns["weight"].nunique()

3

In [174]:
cat_columns["warranty"].unique()

array(['No warranty', '1 year', '2 years', '3 years'], dtype=object)

In [175]:
cat_columns["warranty"].nunique()

4

In [176]:
cat_columns["Touchscreen"].unique()

array(['No', 'Yes'], dtype=object)

In [177]:
cat_columns["Touchscreen"].nunique()

2

In [178]:
cat_columns["msoffice"].unique()

array(['No', 'Yes'], dtype=object)

In [179]:
cat_columns["msoffice"].nunique()

2

In [180]:
cat_columns["rating"].unique()

array(['2 stars', '3 stars', '4 stars', '5 stars', '1 star'], dtype=object)

In [181]:
cat_columns["rating"].nunique()

5

In [182]:
cat_columns['brand'].value_counts()   # Count value in particular feature

brand
ASUS      249
DELL      151
Lenovo    144
HP        136
acer       51
MSI        50
APPLE      28
Avita      14
Name: count, dtype: int64

In [183]:
apple=df[df['brand']=="APPLE"]     # Enter into particular brand
apple

brand processor_brand  ... Number of Ratings Number of Reviews
309  APPLE           Intel  ...                32                 5
310  APPLE           Intel  ...               108                13
407  APPLE           Intel  ...                31                 3
408  APPLE           Intel  ...                91                 5
599  APPLE              M1  ...              6725               629
600  APPLE              M1  ...               640                70
601  APPLE              M1  ...                45                 4
602  APPLE              M1  ...               640                70
603  APPLE              M1  ...               640                70
604  APPLE              M1  ...                45                 4
605  APPLE              M1  ...              6725               629
606  APPLE              M1  ...               640                70
607  APPLE              M1  ...               399                45
608  APPLE              M1  ...               809                91
609  APPLE              M1  ...               809                91
610  APPLE              M1  ...              6725               629
611  APPLE              M1  ...               399                45
612  APPLE              M1  ...                45                 4
613  APPLE              M1  ...                42                 8
614  APPLE              M1  ...                42                 8
615  APPLE              M1  ...                45                 4
616  APPLE              M1  ...              6725               629
617  APPLE              M1  ...               640                70
618  APPLE              M1  ...               640                70
619  APPLE              M1  ...                42                 8
620  APPLE              M1  ...                42                 8
621  APPLE              M1  ...                 3                 1
622  APPLE              M1  ...                42                 8

[28 rows x 19 columns]

In [184]:
asus=df[df['brand']=="ASUS"]      # Enter into particular brand
asus

brand processor_brand  ... Number of Ratings Number of Reviews
0    ASUS           Intel  ...                 3                 0
3    ASUS           Intel  ...                 0                 0
4    ASUS           Intel  ...                 0                 0
5    ASUS           Intel  ...                 0                 0
6    ASUS           Intel  ...                31                 3
..    ...             ...  ...               ...               ...
817  ASUS             AMD  ...                 0                 0
818  ASUS             AMD  ...                 0                 0
819  ASUS             AMD  ...                 0                 0
820  ASUS             AMD  ...                 0                 0
821  ASUS             AMD  ...                 0                 0

[249 rows x 19 columns]

In [185]:
apple.head()

brand processor_brand  ... Number of Ratings Number of Reviews
309  APPLE           Intel  ...                32                 5
310  APPLE           Intel  ...               108                13
407  APPLE           Intel  ...                31                 3
408  APPLE           Intel  ...                91                 5
599  APPLE              M1  ...              6725               629

[5 rows x 19 columns]

In [186]:
apple.tail()

brand processor_brand  ... Number of Ratings Number of Reviews
618  APPLE              M1  ...               640                70
619  APPLE              M1  ...                42                 8
620  APPLE              M1  ...                42                 8
621  APPLE              M1  ...                 3                 1
622  APPLE              M1  ...                42                 8

[5 rows x 19 columns]

In [187]:
apple['processor_brand'].unique()

array(['Intel', 'M1'], dtype=object)

In [188]:
apple_pb=apple[apple['processor_brand']=='M1']
apple_pb

brand processor_brand  ... Number of Ratings Number of Reviews
599  APPLE              M1  ...              6725               629
600  APPLE              M1  ...               640                70
601  APPLE              M1  ...                45                 4
602  APPLE              M1  ...               640                70
603  APPLE              M1  ...               640                70
604  APPLE              M1  ...                45                 4
605  APPLE              M1  ...              6725               629
606  APPLE              M1  ...               640                70
607  APPLE              M1  ...               399                45
608  APPLE              M1  ...               809                91
609  APPLE              M1  ...               809                91
610  APPLE              M1  ...              6725               629
611  APPLE              M1  ...               399                45
612  APPLE              M1  ...                45                 4
613  APPLE              M1  ...                42                 8
614  APPLE              M1  ...                42                 8
615  APPLE              M1  ...                45                 4
616  APPLE              M1  ...              6725               629
617  APPLE              M1  ...               640                70
618  APPLE              M1  ...               640                70
619  APPLE              M1  ...                42                 8
620  APPLE              M1  ...                42                 8
621  APPLE              M1  ...                 3                 1
622  APPLE              M1  ...                42                 8

[24 rows x 19 columns]

In [189]:
apple_pb['Touchscreen'].unique()

array(['No'], dtype=object)

In [190]:
apple_touch=apple_pb[apple_pb['Touchscreen']=='yes']
apple_touch

Empty DataFrame
Columns: [brand, processor_brand, processor_name, processor_gnrtn, ram_gb, ram_type, ssd, hdd, os, os_bit, graphic_card_gb, weight, warranty, Touchscreen, msoffice, Price, rating, Number of Ratings, Number of Reviews]
Index: []

In [191]:
apple.describe()

Price  Number of Ratings  Number of Reviews
count      28.000000          28.000000          28.000000
mean   151707.857143        1207.535714         117.535714
std     54907.255498        2310.990913         214.853866
min     85990.000000           3.000000           1.000000
25%    104990.000000          42.000000           5.000000
50%    132490.000000         253.500000          29.000000
75%    179990.000000         640.000000          70.000000
max    309990.000000        6725.000000         629.000000

In [192]:
max_apple=apple[apple['Price']==309990]
max_apple

brand processor_brand  ... Number of Ratings Number of Reviews
621  APPLE              M1  ...                 3                 1

[1 rows x 19 columns]

In [193]:
# apple =intel ,min 8gb, under 1lakh
apple

brand processor_brand  ... Number of Ratings Number of Reviews
309  APPLE           Intel  ...                32                 5
310  APPLE           Intel  ...               108                13
407  APPLE           Intel  ...                31                 3
408  APPLE           Intel  ...                91                 5
599  APPLE              M1  ...              6725               629
600  APPLE              M1  ...               640                70
601  APPLE              M1  ...                45                 4
602  APPLE              M1  ...               640                70
603  APPLE              M1  ...               640                70
604  APPLE              M1  ...                45                 4
605  APPLE              M1  ...              6725               629
606  APPLE              M1  ...               640                70
607  APPLE              M1  ...               399                45
608  APPLE              M1  ...               809                91
609  APPLE              M1  ...               809                91
610  APPLE              M1  ...              6725               629
611  APPLE              M1  ...               399                45
612  APPLE              M1  ...                45                 4
613  APPLE              M1  ...                42                 8
614  APPLE              M1  ...                42                 8
615  APPLE              M1  ...                45                 4
616  APPLE              M1  ...              6725               629
617  APPLE              M1  ...               640                70
618  APPLE              M1  ...               640                70
619  APPLE              M1  ...                42                 8
620  APPLE              M1  ...                42                 8
621  APPLE              M1  ...                 3                 1
622  APPLE              M1  ...                42                 8

[28 rows x 19 columns]

In [194]:
apple_processor_brand=apple[apple['processor_brand']=='Intel']
apple_processor_brand

brand processor_brand  ... Number of Ratings Number of Reviews
309  APPLE           Intel  ...                32                 5
310  APPLE           Intel  ...               108                13
407  APPLE           Intel  ...                31                 3
408  APPLE           Intel  ...                91                 5

[4 rows x 19 columns]

In [195]:
apple_ram=apple_processor_brand[apple_processor_brand['ram_gb']=='8 GB']
apple_ram

brand processor_brand  ... Number of Ratings Number of Reviews
309  APPLE           Intel  ...                32                 5
310  APPLE           Intel  ...               108                13

[2 rows x 19 columns]

In [196]:
apple_price=apple_ram[apple_ram['Price']=='100000']
apple_price

Empty DataFrame
Columns: [brand, processor_brand, processor_name, processor_gnrtn, ram_gb, ram_type, ssd, hdd, os, os_bit, graphic_card_gb, weight, warranty, Touchscreen, msoffice, Price, rating, Number of Ratings, Number of Reviews]
Index: []

In [197]:
#asus, processor gen10,ddr3,os windows,graphics=4gb,under=50k
asus

brand processor_brand  ... Number of Ratings Number of Reviews
0    ASUS           Intel  ...                 3                 0
3    ASUS           Intel  ...                 0                 0
4    ASUS           Intel  ...                 0                 0
5    ASUS           Intel  ...                 0                 0
6    ASUS           Intel  ...                31                 3
..    ...             ...  ...               ...               ...
817  ASUS             AMD  ...                 0                 0
818  ASUS             AMD  ...                 0                 0
819  ASUS             AMD  ...                 0                 0
820  ASUS             AMD  ...                 0                 0
821  ASUS             AMD  ...                 0                 0

[249 rows x 19 columns]

In [198]:
asus_processor_name=asus[asus['processor_gnrtn']=='10th']
asus_processor_name

brand processor_brand  ... Number of Ratings Number of Reviews
0    ASUS           Intel  ...                 3                 0
3    ASUS           Intel  ...                 0                 0
7    ASUS           Intel  ...                 0                 0
27   ASUS           Intel  ...                67                 3
60   ASUS           Intel  ...                 0                 0
70   ASUS           Intel  ...                 0                 0
86   ASUS           Intel  ...               990               108
89   ASUS           Intel  ...               130                12
98   ASUS           Intel  ...              2551               297
119  ASUS           Intel  ...              4008               519
120  ASUS           Intel  ...              1869               234
122  ASUS           Intel  ...              4008               519
125  ASUS           Intel  ...              4008               519
130  ASUS           Intel  ...                28                 4
136  ASUS           Intel  ...                17                 0
139  ASUS           Intel  ...              4203               490
148  ASUS           Intel  ...                12                 1
150  ASUS           Intel  ...              1850               216
151  ASUS           Intel  ...                43                 7
156  ASUS           Intel  ...                 7                 0
165  ASUS           Intel  ...                12                 0
169  ASUS           Intel  ...                31                 6
180  ASUS           Intel  ...                 0                 0
199  ASUS           Intel  ...              1881               241
219  ASUS           Intel  ...              3712               412
229  ASUS           Intel  ...                35                 2
235  ASUS           Intel  ...              3850               378
250  ASUS           Intel  ...                45                 3
258  ASUS           Intel  ...              1625               152
261  ASUS           Intel  ...                 0                 0
302  ASUS           Intel  ...                11                 3
320  ASUS           Intel  ...                 4                 0
380  ASUS           Intel  ...                 0                 0
381  ASUS           Intel  ...                 4                 0
382  ASUS           Intel  ...                 0                 0
386  ASUS           Intel  ...                 0                 0
402  ASUS           Intel  ...              1365               137
406  ASUS           Intel  ...               187                26
409  ASUS           Intel  ...               844               118
420  ASUS           Intel  ...              1444               179
427  ASUS           Intel  ...                 0                 0
430  ASUS           Intel  ...                 0                 0
432  ASUS           Intel  ...                 0                 0
443  ASUS           Intel  ...                23                 0
465  ASUS           Intel  ...                 1                 1
485  ASUS           Intel  ...                76                 9
486  ASUS           Intel  ...                11                 2
541  ASUS           Intel  ...                17                 1
546  ASUS           Intel  ...                 9                 0
557  ASUS           Intel  ...                 0                 0
565  ASUS           Intel  ...                 3                 0
566  ASUS           Intel  ...                 0                 0
568  ASUS           Intel  ...                 0                 0
576  ASUS           Intel  ...                 0                 0
577  ASUS           Intel  ...                 0                 0
580  ASUS           Intel  ...                25                 4
591  ASUS           Intel  ...                 8                 1
598  ASUS           Intel  ...                 2                 1

[58 rows x 19 columns]

In [199]:
asus_processor_name['ram_type'].unique()

array(['DDR4', 'LPDDR4', 'LPDDR3', 'LPDDR4X'], dtype=object)

In [200]:
asus_ram=asus_processor_name[asus_processor_name['ram_type']=='LPDDR3']
asus_ram

brand processor_brand  ... Number of Ratings Number of Reviews
302  ASUS           Intel  ...                11                 3
381  ASUS           Intel  ...                 4                 0
382  ASUS           Intel  ...                 0                 0
386  ASUS           Intel  ...                 0                 0
541  ASUS           Intel  ...                17                 1
565  ASUS           Intel  ...                 3                 0
566  ASUS           Intel  ...                 0                 0
568  ASUS           Intel  ...                 0                 0
576  ASUS           Intel  ...                 0                 0

[9 rows x 19 columns]

In [201]:
asus_graphic=asus_ram[asus_ram['graphic_card_gb']=='8 GB']

asus_graphic

Empty DataFrame
Columns: [brand, processor_brand, processor_name, processor_gnrtn, ram_gb, ram_type, ssd, hdd, os, os_bit, graphic_card_gb, weight, warranty, Touchscreen, msoffice, Price, rating, Number of Ratings, Number of Reviews]
Index: []

In [202]:
#ACER,INTEL,8GB,BELOW 512GB,WINDOW,4GB,touch,below70k
acer=df[df['brand']=='acer']
acer

brand processor_brand  ... Number of Ratings Number of Reviews
9    acer             AMD  ...              1946               240
10   acer             AMD  ...               259                47
11   acer             AMD  ...               425                67
31   acer           Intel  ...                 0                 0
64   acer           Intel  ...                61                 4
161  acer           Intel  ...                 0                 0
176  acer           Intel  ...                38                 2
196  acer           Intel  ...             10966              1185
197  acer           Intel  ...                 1                 1
198  acer           Intel  ...                31                 6
207  acer           Intel  ...                39                 3
210  acer           Intel  ...                14                 3
212  acer           Intel  ...                33                 7
226  acer           Intel  ...               155                20
244  acer           Intel  ...                 6                 0
257  acer           Intel  ...                17                 1
319  acer           Intel  ...                 0                 0
325  acer           Intel  ...                 0                 0
328  acer           Intel  ...                 4                 1
365  acer           Intel  ...                 0                 0
416  acer           Intel  ...                 0                 0
417  acer           Intel  ...               253                28
419  acer           Intel  ...               118                28
425  acer           Intel  ...                73                21
428  acer           Intel  ...                 0                 0
439  acer           Intel  ...                18                 6
441  acer           Intel  ...                30                 6
444  acer           Intel  ...                32                 1
447  acer           Intel  ...                27                 2
448  acer           Intel  ...                 8                 3
475  acer           Intel  ...                 8                 0
554  acer           Intel  ...                54                 7
575  acer           Intel  ...                 4                 0
582  acer           Intel  ...              2038               313
585  acer           Intel  ...               214                37
586  acer           Intel  ...               342                54
587  acer           Intel  ...                 0                 0
588  acer           Intel  ...                 0                 0
628  acer           Intel  ...               465                89
645  acer             AMD  ...                11                 2
648  acer             AMD  ...                 0                 0
674  acer             AMD  ...                 7                 0
676  acer             AMD  ...                 0                 0
707  acer             AMD  ...               313                39
712  acer             AMD  ...                47                 6
714  acer             AMD  ...                 6                 1
717  acer             AMD  ...                 0                 0
761  acer             AMD  ...                 0                 0
780  acer             AMD  ...                 0                 0
793  acer             AMD  ...               272                36
794  acer             AMD  ...               141                24

[51 rows x 19 columns]

In [203]:
acer_i=acer[acer['processor_brand']=='Intel']
acer_i

brand processor_brand  ... Number of Ratings Number of Reviews
31   acer           Intel  ...                 0                 0
64   acer           Intel  ...                61                 4
161  acer           Intel  ...                 0                 0
176  acer           Intel  ...                38                 2
196  acer           Intel  ...             10966              1185
197  acer           Intel  ...                 1                 1
198  acer           Intel  ...                31                 6
207  acer           Intel  ...                39                 3
210  acer           Intel  ...                14                 3
212  acer           Intel  ...                33                 7
226  acer           Intel  ...               155                20
244  acer           Intel  ...                 6                 0
257  acer           Intel  ...                17                 1
319  acer           Intel  ...                 0                 0
325  acer           Intel  ...                 0                 0
328  acer           Intel  ...                 4                 1
365  acer           Intel  ...                 0                 0
416  acer           Intel  ...                 0                 0
417  acer           Intel  ...               253                28
419  acer           Intel  ...               118                28
425  acer           Intel  ...                73                21
428  acer           Intel  ...                 0                 0
439  acer           Intel  ...                18                 6
441  acer           Intel  ...                30                 6
444  acer           Intel  ...                32                 1
447  acer           Intel  ...                27                 2
448  acer           Intel  ...                 8                 3
475  acer           Intel  ...                 8                 0
554  acer           Intel  ...                54                 7
575  acer           Intel  ...                 4                 0
582  acer           Intel  ...              2038               313
585  acer           Intel  ...               214                37
586  acer           Intel  ...               342                54
587  acer           Intel  ...                 0                 0
588  acer           Intel  ...                 0                 0
628  acer           Intel  ...               465                89

[36 rows x 19 columns]

In [204]:
acer_r=acer_i[acer_i['ram_gb']=='8 GB']
acer_r

brand processor_brand  ... Number of Ratings Number of Reviews
31   acer           Intel  ...                 0                 0
176  acer           Intel  ...                38                 2
196  acer           Intel  ...             10966              1185
197  acer           Intel  ...                 1                 1
198  acer           Intel  ...                31                 6
207  acer           Intel  ...                39                 3
210  acer           Intel  ...                14                 3
212  acer           Intel  ...                33                 7
226  acer           Intel  ...               155                20
244  acer           Intel  ...                 6                 0
257  acer           Intel  ...                17                 1
319  acer           Intel  ...                 0                 0
325  acer           Intel  ...                 0                 0
328  acer           Intel  ...                 4                 1
365  acer           Intel  ...                 0                 0
416  acer           Intel  ...                 0                 0
417  acer           Intel  ...               253                28
419  acer           Intel  ...               118                28
425  acer           Intel  ...                73                21
428  acer           Intel  ...                 0                 0
439  acer           Intel  ...                18                 6
441  acer           Intel  ...                30                 6
444  acer           Intel  ...                32                 1
447  acer           Intel  ...                27                 2
448  acer           Intel  ...                 8                 3

[25 rows x 19 columns]

In [205]:
acer_s=acer_r[acer_r['ssd']>='512 GB']
acer_s

brand processor_brand  ... Number of Ratings Number of Reviews
226  acer           Intel  ...               155                20
244  acer           Intel  ...                 6                 0
257  acer           Intel  ...                17                 1
319  acer           Intel  ...                 0                 0
325  acer           Intel  ...                 0                 0
328  acer           Intel  ...                 4                 1
365  acer           Intel  ...                 0                 0

[7 rows x 19 columns]

In [206]:
acer_o=acer_s[acer_s['os']=='Windows']
acer_o

brand processor_brand  ... Number of Ratings Number of Reviews
226  acer           Intel  ...               155                20
244  acer           Intel  ...                 6                 0
257  acer           Intel  ...                17                 1
319  acer           Intel  ...                 0                 0
325  acer           Intel  ...                 0                 0
328  acer           Intel  ...                 4                 1
365  acer           Intel  ...                 0                 0

[7 rows x 19 columns]

In [207]:
acer_g=acer_o[acer_o['graphic_card_gb']=='4 GB']
acer_g

brand processor_brand  ... Number of Ratings Number of Reviews
325  acer           Intel  ...                 0                 0

[1 rows x 19 columns]

In [208]:
acer_t=acer_g[acer_g['Touchscreen']=='Yes']
acer_t

Empty DataFrame
Columns: [brand, processor_brand, processor_name, processor_gnrtn, ram_gb, ram_type, ssd, hdd, os, os_bit, graphic_card_gb, weight, warranty, Touchscreen, msoffice, Price, rating, Number of Ratings, Number of Reviews]
Index: []

In [209]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 823 entries, 0 to 822
Data columns (total 19 columns):
 #   Column             Non-Null Count  Dtype 
---  ------             --------------  ----- 
 0   brand              823 non-null    object
 1   processor_brand    823 non-null    object
 2   processor_name     823 non-null    object
 3   processor_gnrtn    823 non-null    object
 4   ram_gb             823 non-null    object
 5   ram_type           823 non-null    object
 6   ssd                823 non-null    object
 7   hdd                823 non-null    object
 8   os                 823 non-null    object
 9   os_bit             823 non-null    object
 10  graphic_card_gb    823 non-null    object
 11  weight             823 non-null    object
 12  warranty           823 non-null    object
 13  Touchscreen        823 non-null    object
 14  msoffice           823 non-null    object
 15  Price              823 non-null    int64 
 16  rating             823 non-null    object
 1

In [210]:
df.isnull().sum()

brand                0
processor_brand      0
processor_name       0
processor_gnrtn      0
ram_gb               0
ram_type             0
ssd                  0
hdd                  0
os                   0
os_bit               0
graphic_card_gb      0
weight               0
warranty             0
Touchscreen          0
msoffice             0
Price                0
rating               0
Number of Ratings    0
Number of Reviews    0
dtype: int64

In [211]:
df.duplicated().sum()

np.int64(21)

In [212]:
df.drop_duplicates(inplace=True)

In [213]:
df.duplicated().sum()

np.int64(0)

In [214]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 802 entries, 0 to 822
Data columns (total 19 columns):
 #   Column             Non-Null Count  Dtype 
---  ------             --------------  ----- 
 0   brand              802 non-null    object
 1   processor_brand    802 non-null    object
 2   processor_name     802 non-null    object
 3   processor_gnrtn    802 non-null    object
 4   ram_gb             802 non-null    object
 5   ram_type           802 non-null    object
 6   ssd                802 non-null    object
 7   hdd                802 non-null    object
 8   os                 802 non-null    object
 9   os_bit             802 non-null    object
 10  graphic_card_gb    802 non-null    object
 11  weight             802 non-null    object
 12  warranty           802 non-null    object
 13  Touchscreen        802 non-null    object
 14  msoffice           802 non-null    object
 15  Price              802 non-null    int64 
 16  rating             802 non-null    object
 17  Nu

In [215]:
df.drop(['rating','Number of Ratings','Number of Reviews'],axis=1,inplace=True)


In [216]:
df.duplicated().sum() # Check duplicate value

np.int64(16)

In [217]:
df.drop_duplicates(inplace=True)
df.duplicated().sum()

np.int64(0)

In [218]:
df

brand processor_brand processor_name  ... Touchscreen msoffice   Price
0      ASUS           Intel        Core i3  ...          No       No   34649
1    Lenovo           Intel        Core i3  ...          No       No   38999
2    Lenovo           Intel        Core i3  ...          No       No   39999
3      ASUS           Intel        Core i5  ...          No       No   69990
4      ASUS           Intel   Celeron Dual  ...          No       No   26990
..      ...             ...            ...  ...         ...      ...     ...
818    ASUS             AMD        Ryzen 9  ...          No       No  135990
819    ASUS             AMD        Ryzen 9  ...          No       No  144990
820    ASUS             AMD        Ryzen 9  ...          No       No  149990
821    ASUS             AMD        Ryzen 9  ...          No       No  142990
822  Lenovo             AMD        Ryzen 5  ...          No       No   57490

[786 rows x 16 columns]

## Now conversion of cat data into num data

In [219]:
import sklearn

In [220]:
from sklearn.preprocessing import LabelEncoder,OneHotEncoder

In [221]:
encoder=LabelEncoder()

In [222]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 786 entries, 0 to 822
Data columns (total 16 columns):
 #   Column           Non-Null Count  Dtype 
---  ------           --------------  ----- 
 0   brand            786 non-null    object
 1   processor_brand  786 non-null    object
 2   processor_name   786 non-null    object
 3   processor_gnrtn  786 non-null    object
 4   ram_gb           786 non-null    object
 5   ram_type         786 non-null    object
 6   ssd              786 non-null    object
 7   hdd              786 non-null    object
 8   os               786 non-null    object
 9   os_bit           786 non-null    object
 10  graphic_card_gb  786 non-null    object
 11  weight           786 non-null    object
 12  warranty         786 non-null    object
 13  Touchscreen      786 non-null    object
 14  msoffice         786 non-null    object
 15  Price            786 non-null    int64 
dtypes: int64(1), object(15)
memory usage: 104.4+ KB


In [223]:
df['brand'].unique()

array(['ASUS', 'Lenovo', 'acer', 'Avita', 'HP', 'DELL', 'MSI', 'APPLE'],
      dtype=object)

In [224]:
output=encoder.fit_transform(df['brand'])
output.shape
output
df['brand']=output
df['brand'].unique()

array([1, 5, 7, 2, 4, 3, 6, 0])

In [225]:
df['processor_brand'].unique()

array(['Intel', 'AMD', 'M1'], dtype=object)

In [226]:
ouptut=encoder.fit_transform(df['processor_brand'])
output.shape
output
df['processor_brand']=output
df['processor_brand'].unique()

array([1, 5, 7, 2, 4, 3, 6, 0])

In [227]:
df['processor_name'].unique()

array(['Core i3', 'Core i5', 'Celeron Dual', 'Ryzen 5', 'Core i7',
       'Core i9', 'M1', 'Pentium Quad', 'Ryzen 3', 'Ryzen 7', 'Ryzen 9'],
      dtype=object)

In [228]:
output=encoder.fit_transform(df['processor_name'])
output.shape
output
df['processor_name']=output
df['processor_name'].unique()

array([ 1,  2,  0,  8,  3,  4,  5,  6,  7,  9, 10])

In [229]:
df['processor_gnrtn'].unique()

array(['10th', 'Not Available', '11th', '7th', '8th', '9th', '4th',
       '12th'], dtype=object)

In [230]:
output=encoder.fit_transform(df['processor_gnrtn'])
output.shape
output
df['processor_gnrtn']=output
df['processor_gnrtn'].unique()

array([0, 7, 1, 4, 5, 6, 3, 2])

In [231]:
df['ram_gb'].unique()

array(['4 GB', '8 GB', '16 GB', '32 GB'], dtype=object)

In [232]:
output=encoder.fit_transform(df['ram_gb'])
df['ram_gb']=output
df['ram_gb'].unique()

array([2, 3, 0, 1])

In [233]:
df['ram_type'].unique()

array(['DDR4', 'LPDDR4', 'LPDDR4X', 'DDR5', 'DDR3', 'LPDDR3'],
      dtype=object)

In [234]:
output=encoder.fit_transform(df['ram_type'])
df['ram_type']=output
df['ram_type'].unique()

array([1, 4, 5, 2, 0, 3])

In [235]:
df['ssd'].unique()

array(['0 GB', '512 GB', '256 GB', '128 GB', '1024 GB', '2048 GB',
       '3072 GB'], dtype=object)

In [236]:
ouptut=encoder.fit_transform(df['ssd'])
df['ssd']=output
df['ssd'].unique()

array([1, 4, 5, 2, 0, 3])

In [237]:
df['hdd'].unique()

array(['1024 GB', '0 GB', '512 GB', '2048 GB'], dtype=object)

In [238]:
output=encoder.fit_transform(df['hdd'])
df['hdd']=output
df['hdd'].unique()

array([1, 0, 3, 2])

In [239]:
df['os'].unique()

array(['Windows', 'DOS', 'Mac'], dtype=object)

In [240]:
output=encoder.fit_transform(df['os'])
df['os']=output
df['os'].unique()

array([2, 0, 1])

In [241]:
df['graphic_card_gb'].unique()

array(['0 GB', '2 GB', '4 GB', '6 GB', '8 GB'], dtype=object)

In [242]:
output=encoder.fit_transform(df['graphic_card_gb'])
df['graphic_card_gb']=output
df['graphic_card_gb'].unique()

array([0, 1, 2, 3, 4])

In [243]:
df['weight'].unique()

array(['Casual', 'ThinNlight', 'Gaming'], dtype=object)

In [244]:
output=encoder.fit_transform(df['weight'])
df['weight']=output
df['weight'].unique()

array([0, 2, 1])

In [245]:
df['warranty'].unique()

array(['No warranty', '1 year', '2 years', '3 years'], dtype=object)

In [246]:
output=encoder.fit_transform(df['warranty'])
df['warranty']=output
df['warranty'].unique()

array([3, 0, 1, 2])

In [247]:
df['os_bit'].unique()

array(['64-bit', '32-bit'], dtype=object)

In [248]:
output=encoder.fit_transform(df['os_bit'])
df['os_bit']=output
df['os_bit'].unique()

array([1, 0])

In [249]:
df['Touchscreen'].unique()

array(['No', 'Yes'], dtype=object)

In [250]:
output=encoder.fit_transform(df['Touchscreen'])
df['Touchscreen']=output
df['Touchscreen'].unique()

array([0, 1])

In [251]:
df['msoffice'].unique()

array(['No', 'Yes'], dtype=object)

In [252]:
output=encoder.fit_transform(df['msoffice'])
df['msoffice']=output
df['msoffice'].unique()

array([0, 1])

In [253]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 786 entries, 0 to 822
Data columns (total 16 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   brand            786 non-null    int64
 1   processor_brand  786 non-null    int64
 2   processor_name   786 non-null    int64
 3   processor_gnrtn  786 non-null    int64
 4   ram_gb           786 non-null    int64
 5   ram_type         786 non-null    int64
 6   ssd              786 non-null    int64
 7   hdd              786 non-null    int64
 8   os               786 non-null    int64
 9   os_bit           786 non-null    int64
 10  graphic_card_gb  786 non-null    int64
 11  weight           786 non-null    int64
 12  warranty         786 non-null    int64
 13  Touchscreen      786 non-null    int64
 14  msoffice         786 non-null    int64
 15  Price            786 non-null    int64
dtypes: int64(16)
memory usage: 104.4 KB


In [254]:
df.duplicated().sum()
df.drop_duplicates(inplace=True)
df.duplicated().sum()

np.int64(0)

### Now split the data

In [255]:
x=df.drop(['Price'],axis=1)
y=df[['Price']]
y

Price
0     34649
1     38999
2     39999
3     69990
4     26990
..      ...
818  135990
819  144990
820  149990
821  142990
822   57490

[784 rows x 1 columns]

In [256]:
x

brand  processor_brand  processor_name  ...  warranty  Touchscreen  msoffice
0        1                1               1  ...         3            0         0
1        5                5               1  ...         3            0         0
2        5                5               1  ...         3            0         0
3        1                1               2  ...         3            0         0
4        1                1               0  ...         3            0         0
..     ...              ...             ...  ...       ...          ...       ...
818      1                1              10  ...         0            0         0
819      1                1              10  ...         0            0         0
820      1                1              10  ...         0            0         0
821      1                1              10  ...         0            0         0
822      5                5               8  ...         3            0         0

[784 rows x 15 columns]

In [257]:
from sklearn.model_selection import train_test_split

In [258]:
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=42)

In [259]:
x_train.shape,x_test.shape,y_train.shape,y_test.shape

((627, 15), (157, 15), (627, 1), (157, 1))

In [260]:
x_train.head()
x_train.shape

(627, 15)

In [261]:
y_train.head()
y_train.shape

(627, 1)

In [262]:
x_test

brand  processor_brand  processor_name  ...  warranty  Touchscreen  msoffice
632      1                1               6  ...         3            0         0
624      1                1               6  ...         3            1         0
218      4                4               2  ...         0            0         1
673      4                4               8  ...         0            0         1
183      3                3               1  ...         0            0         1
..     ...              ...             ...  ...       ...          ...       ...
82       3                3               1  ...         0            0         0
156      1                1               1  ...         3            0         0
347      3                3               2  ...         2            0         0
256      4                4               2  ...         0            0         1
587      7                7               4  ...         0            0         0

[157 rows x 15 columns]

In [263]:
y_test

Price
632   27990
624   58100
218   67990
673   48990
183   41390
..      ...
82    48500
156   38000
347   71990
256   66999
587  169990

[157 rows x 1 columns]

In [264]:
df.drop_duplicates(inplace=True)
df.duplicated().sum()

np.int64(0)

#### **DECISION TREE**

In [272]:
from sklearn.tree import DecisionTreeRegressor,DecisionTreeClassifier

In [273]:
obj=DecisionTreeRegressor()
obj.fit(x_train,y_train)

DecisionTreeRegressor()

In [274]:
print("Testing score",obj.score(x_test,y_test))

Testing score 0.49074146298504906


In [275]:
print("Training score",obj.score(x_train,y_train))

Training score 0.975191971323835


In [ ]:
obj1=DecisionTreeClassifier()
obj1.fit(x_train,y_train)

DecisionTreeClassifier()

In [277]:
print("Testing score",obj1.score(x_test,y_test))
print("Training score",obj1.score(x_train,y_train))

Testing score 0.012738853503184714
Training score 0.7878787878787878
