In [323]:
import numpy as np # Data manipulation , solved math problem

In [324]:
lst=list(range(1,25))
print(len(lst))            # Length of list
arr=np.array(lst)          # Conversion
print(type(arr))           # Type
print(type(lst))

24
<class 'numpy.ndarray'>
<class 'list'>


In [325]:
arr=np.array([1,2,3,4])     # Create np array
arr                         # Single arr

array([1, 2, 3, 4])

In [326]:
arr=np.arange(1,25)          # arange ()- ussed to create array without range function
arr 

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24])

In [327]:
arr=np.array([[1,2,3,4],[1,2,3,4]])        # 2d array
arr

array([[1, 2, 3, 4],
       [1, 2, 3, 4]])

In [328]:
arr=np.zeros((3,4))                        # Display zeroes as values of array
arr

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [329]:
# 3d array(3 block ,3 rows,3 column)
arr=np.array ([[[1, 2, 3], [4, 5, 6], [4, 5, 6]],[[7, 8, 9], [10, 11, 12], [4, 5, 6]],[[13, 14, 15], [16, 17, 18], [4, 5, 6]]])
arr

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12],
        [ 4,  5,  6]],

       [[13, 14, 15],
        [16, 17, 18],
        [ 4,  5,  6]]])

In [330]:
arr=np.ones((6,10))                        # Display ones as values of array
arr

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

In [331]:
arr=np.ones((3,4,5))                        # Display ones as values of array
arr

array([[[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]]])

In [332]:
# Equal space in 1d array
arr=np.linspace(0,10,5)            # Start , End, number of values
arr

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

In [333]:
# Equal space in 2d using reshape(used to covert 1d to 2d)
arr=np.linspace(0,10,5).reshape(5,1)                      # 5 row 1 column
arr

array([[ 0. ],
       [ 2.5],
       [ 5. ],
       [ 7.5],
       [10. ]])

In [334]:
# Equal space in 2d using reshape(used to covert 1d to 2d)
arr=np.linspace(0,10,5)                                    # Start , End , number of values
arr.reshape(5,1)                                           # 5 row 1 column

array([[ 0. ],
       [ 2.5],
       [ 5. ],
       [ 7.5],
       [10. ]])

In [335]:
#reshaping 1d to 2d with reshape()
arr=np.arange(0,30)                # Start , End
arr
arr.reshape(5,6)                   # Row , Column


array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29]])

In [336]:
arr.shape                 # Check no of values

(30,)

In [337]:
arr
arr.reshape(3,5,2)               # Make a 3d array

array([[[ 0,  1],
        [ 2,  3],
        [ 4,  5],
        [ 6,  7],
        [ 8,  9]],

       [[10, 11],
        [12, 13],
        [14, 15],
        [16, 17],
        [18, 19]],

       [[20, 21],
        [22, 23],
        [24, 25],
        [26, 27],
        [28, 29]]])

In [338]:
arr.shape

(30,)

In [339]:
# Random  initilization
arr=np.random.randint(1,31,30)        # Lower limit , Upper limit , Total no
arr

array([ 8, 22,  1,  1, 18, 13, 26, 22, 22, 23, 21, 11,  3, 16, 10,  9,  3,
       27,  6,  7, 29,  6, 15,  4, 18, 12,  9, 15, 10, 19], dtype=int32)

In [340]:
# 2d array
arr=np.random.randint(1,5,(5,6))     # Lower limit , Upper limit , (Row , Column)
arr

array([[2, 1, 4, 4, 3, 4],
       [3, 4, 2, 3, 4, 3],
       [2, 4, 4, 3, 1, 4],
       [3, 1, 4, 1, 2, 4],
       [3, 1, 4, 3, 4, 4]], dtype=int32)

In [341]:
# 3d array
arr=np.random.randint(1,5,(3,5,2))    # Lower limit , Upper limit , ( Block, Row , Column)
arr

array([[[3, 3],
        [3, 4],
        [4, 3],
        [4, 2],
        [2, 1]],

       [[2, 1],
        [4, 4],
        [1, 1],
        [3, 4],
        [3, 4]],

       [[2, 2],
        [2, 2],
        [4, 1],
        [4, 3],
        [4, 1]]], dtype=int32)

In [342]:
arr=np.random.random(10)          # Default element range 0 to 1
arr

array([0.22258411, 0.14260083, 0.82490368, 0.25488217, 0.29443338,
       0.3621466 , 0.00573372, 0.39510457, 0.0088327 , 0.99021374])

In [343]:
arr=np.random.randint(10)         # Range
arr

2

In [344]:
arr=np.random.random((5,2))   # 1d to 2d array using random
arr

array([[0.74929511, 0.13293   ],
       [0.80304498, 0.59562944],
       [0.57087079, 0.88541107],
       [0.20303209, 0.45505401],
       [0.75596654, 0.01439556]])

In [345]:
arr=np.random.random(((5,2,1)))  # 2d to 3d array using random
arr

array([[[0.11582482],
        [0.76435571]],

       [[0.73915168],
        [0.89506281]],

       [[0.18238353],
        [0.49859843]],

       [[0.88308942],
        [0.05836145]],

       [[0.91507225],
        [0.83050639]]])

In [346]:
arr=np.arange(60).reshape(10,6)
arr
#arr.dtype                          # Datatype - int64
#arr.shape                         # Shape - (10,6)
#arr.ndim                          # Dimension - 2d
#arr.size                          # Size - 60

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35],
       [36, 37, 38, 39, 40, 41],
       [42, 43, 44, 45, 46, 47],
       [48, 49, 50, 51, 52, 53],
       [54, 55, 56, 57, 58, 59]])

In [347]:
arr.flatten()      # Flatten used to covert 3d or 2d into 1d array

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59])

In [348]:
arr.ravel()    # Used to covert 3d or 2d into 1d array

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59])

In [349]:
lst=list(range(1,25))
arr=np.array(lst)
arr


array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24])

In [350]:
arr.shape

(24,)

In [351]:
arr.T.shape           # Transpose shape

(24,)

In [352]:
lst=[[1,2,3],[4,5,6],[7,8,9],[10,11,12]]
arr=np.array(lst)
arr


array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [353]:
arr.shape

(4, 3)

In [354]:
arr.T.shape       # Transpose

(3, 4)

In [355]:
arr.T            #  Print transpose matrix

array([[ 1,  4,  7, 10],
       [ 2,  5,  8, 11],
       [ 3,  6,  9, 12]])

In [356]:
arr=np.arange(60)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59])

In [357]:
arr=arr.reshape((5,12))
arr

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35],
       [36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47],
       [48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59]])

In [358]:
arr.T

array([[ 0, 12, 24, 36, 48],
       [ 1, 13, 25, 37, 49],
       [ 2, 14, 26, 38, 50],
       [ 3, 15, 27, 39, 51],
       [ 4, 16, 28, 40, 52],
       [ 5, 17, 29, 41, 53],
       [ 6, 18, 30, 42, 54],
       [ 7, 19, 31, 43, 55],
       [ 8, 20, 32, 44, 56],
       [ 9, 21, 33, 45, 57],
       [10, 22, 34, 46, 58],
       [11, 23, 35, 47, 59]])

In [359]:
arr.T.shape

(12, 5)

In [360]:
arr=np.arange(60)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59])

In [361]:
arr[2]         # Access the element of array in 1d array

np.int64(2)

In [362]:
arr[3:11]      # Access multiple values

array([ 3,  4,  5,  6,  7,  8,  9, 10])

In [363]:
arr[0:22:2]   # Start , End , Gap

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [364]:
arr=np.arange(60)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59])

In [365]:
arr=arr.reshape((12,5))
arr

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34],
       [35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44],
       [45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54],
       [55, 56, 57, 58, 59]])

In [366]:
arr[1]                   # Accessing 2nd row

array([5, 6, 7, 8, 9])

In [367]:
arr[1,1]              # Accesing particualr position

np.int64(6)

In [368]:
arr[0:5,1:2]      # 0 to 5 row and 1 column

array([[ 1],
       [ 6],
       [11],
       [16],
       [21]])

In [369]:
arr

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34],
       [35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44],
       [45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54],
       [55, 56, 57, 58, 59]])

In [370]:
arr[11,4]     # Last element

np.int64(59)

In [371]:
arr[11][-1]   # Last element

np.int64(59)

In [372]:
arr[-1][-1]    # Last element

np.int64(59)

In [ ]:
arr[-1][:5]        # Last row

array([55, 56, 57, 58, 59])

In [ ]:
arr[:4][-1]           # Row

array([15, 16, 17, 18, 19])

In [ ]:
arr[4,2]=100      # Replace value
arr

array([[  0,   1,   2,   3,   4],
       [  5,   6,   7,   8,   9],
       [ 10,  11,  12,  13,  14],
       [ 15,  16,  17,  18,  19],
       [ 20,  21, 100,  23,  24],
       [ 25,  26,  27,  28,  29],
       [ 30,  31,  32,  33,  34],
       [ 35,  36,  37,  38,  39],
       [ 40,  41,  42,  43,  44],
       [ 45,  46,  47,  48,  49],
       [ 50,  51,  52,  53,  54],
       [ 55,  56,  57,  58,  59]])

In [376]:
arr=np.arange(225).reshape(5,15,3)
arr

array([[[  0,   1,   2],
        [  3,   4,   5],
        [  6,   7,   8],
        [  9,  10,  11],
        [ 12,  13,  14],
        [ 15,  16,  17],
        [ 18,  19,  20],
        [ 21,  22,  23],
        [ 24,  25,  26],
        [ 27,  28,  29],
        [ 30,  31,  32],
        [ 33,  34,  35],
        [ 36,  37,  38],
        [ 39,  40,  41],
        [ 42,  43,  44]],

       [[ 45,  46,  47],
        [ 48,  49,  50],
        [ 51,  52,  53],
        [ 54,  55,  56],
        [ 57,  58,  59],
        [ 60,  61,  62],
        [ 63,  64,  65],
        [ 66,  67,  68],
        [ 69,  70,  71],
        [ 72,  73,  74],
        [ 75,  76,  77],
        [ 78,  79,  80],
        [ 81,  82,  83],
        [ 84,  85,  86],
        [ 87,  88,  89]],

       [[ 90,  91,  92],
        [ 93,  94,  95],
        [ 96,  97,  98],
        [ 99, 100, 101],
        [102, 103, 104],
        [105, 106, 107],
        [108, 109, 110],
        [111, 112, 113],
        [114, 115, 116],
        [117, 118, 11

In [377]:
arr.ndim

3

In [ ]:
arr[1]            # Acesss table block

array([[45, 46, 47],
       [48, 49, 50],
       [51, 52, 53],
       [54, 55, 56],
       [57, 58, 59],
       [60, 61, 62],
       [63, 64, 65],
       [66, 67, 68],
       [69, 70, 71],
       [72, 73, 74],
       [75, 76, 77],
       [78, 79, 80],
       [81, 82, 83],
       [84, 85, 86],
       [87, 88, 89]])

In [ ]:
arr[0][2:7]          # Block 0 and all specific rows

array([[ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14],
       [15, 16, 17],
       [18, 19, 20]])

In [ ]:
arr[0][2:7][0]        # Row and Column in a block

array([6, 7, 8])

In [381]:
arr[:,0:1,0:1]

array([[[  0]],

       [[ 45]],

       [[ 90]],

       [[135]],

       [[180]]])

In [ ]:
arr[2][3][1]=100000000     # Change value


In [383]:
arr[2][3]

array([       99, 100000000,       101])

In [384]:
arr=np.arange(60)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59])

In [385]:
arr=arr.reshape((12,5))
arr

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34],
       [35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44],
       [45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54],
       [55, 56, 57, 58, 59]])

In [ ]:
arr +2        # Add in matrix

array([[ 2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16],
       [17, 18, 19, 20, 21],
       [22, 23, 24, 25, 26],
       [27, 28, 29, 30, 31],
       [32, 33, 34, 35, 36],
       [37, 38, 39, 40, 41],
       [42, 43, 44, 45, 46],
       [47, 48, 49, 50, 51],
       [52, 53, 54, 55, 56],
       [57, 58, 59, 60, 61]])

In [ ]:
arr *2       # Multiply in matrix

array([[  0,   2,   4,   6,   8],
       [ 10,  12,  14,  16,  18],
       [ 20,  22,  24,  26,  28],
       [ 30,  32,  34,  36,  38],
       [ 40,  42,  44,  46,  48],
       [ 50,  52,  54,  56,  58],
       [ 60,  62,  64,  66,  68],
       [ 70,  72,  74,  76,  78],
       [ 80,  82,  84,  86,  88],
       [ 90,  92,  94,  96,  98],
       [100, 102, 104, 106, 108],
       [110, 112, 114, 116, 118]])

In [ ]:
arr -1       # Subtract in matrix

array([[-1,  0,  1,  2,  3],
       [ 4,  5,  6,  7,  8],
       [ 9, 10, 11, 12, 13],
       [14, 15, 16, 17, 18],
       [19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28],
       [29, 30, 31, 32, 33],
       [34, 35, 36, 37, 38],
       [39, 40, 41, 42, 43],
       [44, 45, 46, 47, 48],
       [49, 50, 51, 52, 53],
       [54, 55, 56, 57, 58]])

In [ ]:
arr /2        # Division in matrix

array([[ 0. ,  0.5,  1. ,  1.5,  2. ],
       [ 2.5,  3. ,  3.5,  4. ,  4.5],
       [ 5. ,  5.5,  6. ,  6.5,  7. ],
       [ 7.5,  8. ,  8.5,  9. ,  9.5],
       [10. , 10.5, 11. , 11.5, 12. ],
       [12.5, 13. , 13.5, 14. , 14.5],
       [15. , 15.5, 16. , 16.5, 17. ],
       [17.5, 18. , 18.5, 19. , 19.5],
       [20. , 20.5, 21. , 21.5, 22. ],
       [22.5, 23. , 23.5, 24. , 24.5],
       [25. , 25.5, 26. , 26.5, 27. ],
       [27.5, 28. , 28.5, 29. , 29.5]])

In [390]:
arr=arr.reshape(12,5)
arr

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34],
       [35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44],
       [45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54],
       [55, 56, 57, 58, 59]])

In [391]:
arr1=arr.reshape(12,5)
arr1

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34],
       [35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44],
       [45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54],
       [55, 56, 57, 58, 59]])

In [ ]:
arr+arr1     # Add 2d matrix

array([[  0,   2,   4,   6,   8],
       [ 10,  12,  14,  16,  18],
       [ 20,  22,  24,  26,  28],
       [ 30,  32,  34,  36,  38],
       [ 40,  42,  44,  46,  48],
       [ 50,  52,  54,  56,  58],
       [ 60,  62,  64,  66,  68],
       [ 70,  72,  74,  76,  78],
       [ 80,  82,  84,  86,  88],
       [ 90,  92,  94,  96,  98],
       [100, 102, 104, 106, 108],
       [110, 112, 114, 116, 118]])

In [ ]:
arr=np.arange(1,10)     # Add 1d matrix
arr1=np.arange(1,10)
arr+arr1

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18])

In [394]:
arr*arr1

array([ 1,  4,  9, 16, 25, 36, 49, 64, 81])

In [ ]:
x=list(range(1,10))      # Add list
print(x)
y=list(range(11,20))
print(y)
x+y

[1, 2, 3, 4, 5, 6, 7, 8, 9]
[11, 12, 13, 14, 15, 16, 17, 18, 19]


[1, 2, 3, 4, 5, 6, 7, 8, 9, 11, 12, 13, 14, 15, 16, 17, 18, 19]

In [396]:
x=np.array(x)
y=np.array(y)
x+y

array([12, 14, 16, 18, 20, 22, 24, 26, 28])

In [397]:
x*y

array([ 11,  24,  39,  56,  75,  96, 119, 144, 171])

In [5]:
# Write a program to read a file
file_path = r'C:\Users\DELL\.vscode\Arya College\OOPS\example.txt'
with open(file_path, 'r') as file:
    lines = file.readlines()
    for line in lines:
        print(line.strip())  # Print each line without leading/trailing whitespace

Hi! My name is Chirag
